server.port: 8080
jwt.secretKey: ${JWT_SECRET_KEY}

#api-gateway-config
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: agent-service
          uri: ${AGENT_SERVICE_URL:http://localhost:9060}
          predicates:
            - Path=/api/v1/agent/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter

        - id: user-service
          uri: ${USER_SERVICE_URL:http://localhost:9010}
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter

        - id: user-service-oauth2
          uri: ${USER_SERVICE_URL:http://localhost:9010}
          predicates:
            - Path=/users/oauth2/**, /users/login/oauth2/**
          filters:
            - AuthenticationFilter
            - PreserveHostHeader

        - id: product-service
          uri: ${PRODUCT_SERVICE_URL:http://localhost:9020}
          predicates:
            - Path=/api/v1/products/**, /api/v1/admin/products/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter
        #            - RewritePath=/api/v1/(?<segment>.*), /${segment}

        - id: cart-service
          uri: ${CART_SERVICE_URL:http://localhost:9030}
          predicates:
            - Path=/api/v1/cart/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter

        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://localhost:9040}
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter

        - id: payment-service
          uri: ${PAYMENT_SERVICE_URL:http://localhost:9050}
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter

#eureka-configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
