apiVersion: v1
kind: Secret
metadata:
  name: ai-ecommerce-secret
  namespace: ai-ecommerce
type: Opaque
stringData:
  # USER-SERVICE
  JWT_SECRET_KEY: "Change-me"
  DB_USERNAME: "Change-me"
  DB_PASSWORD: "Change-me"
  GOOGLE_CLIENT_ID: "change-me"
  GOOGLE_CLIENT_SECRET: "change-me"
