apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-user-data
  namespace: ai-ecommerce
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
