apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: ai-ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway

  template:
    metadata:
      labels:
        app: api-gateway

    spec:
      containers:
        - name: api-gateway
          image: krishnakant2001/api-gateway
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-ecommerce-secret
                  key: JWT_SECRET_KEY
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: USER_SERVICE_URL
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: PRODUCT_SERVICE_URL
            - name: CART_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: CART_SERVICE_URL
            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: ORDER_SERVICE_URL
            - name: PAYMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: PAYMENT_SERVICE_URL
            - name: AGENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: AGENT_SERVICE_URL
          resources:
            limits:
              memory: "256Mi"
              cpu: "512m"
            requests:
              memory: "128Mi"
              cpu: "256m"
          ports:
            - containerPort: 8080
