package com.strikerkk.aicommerce.cart_service.entity;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.lang.reflect.Field;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

@DisplayName("Cart entity")
class CartTest {

    private Field field(String name) throws NoSuchFieldException {
        return Cart.class.getDeclaredField(name);
    }

    @Test
    @DisplayName("the builder populates every field")
    void builderPopulatesEveryField() {
        LocalDateTime now = LocalDateTime.now();
        CartItem item = CartItem.builder().build();

        Cart cart = Cart.builder()
                .id(7L)
                .userId(42L)
                .cartItems(new ArrayList<>(List.of(item)))
                .createdAt(now)
                .updatedAt(now)
                .build();

        assertThat(cart.getId()).isEqualTo(7L);
        assertThat(cart.getUserId()).isEqualTo(42L);
        assertThat(cart.getCartItems()).containsExactly(item);
        assertThat(cart.getCreatedAt()).isEqualTo(now);
        assertThat(cart.getUpdatedAt()).isEqualTo(now);
    }

    @Test
    @DisplayName("cartItems defaults to an empty, mutable list so the service can add straight away")
    void cartItemsDefaultsToAnEmptyMutableList() {
        Cart cart = Cart.builder().userId(42L).build();

        assertThat(cart.getCartItems()).isNotNull().isEmpty();

        cart.getCartItems().add(CartItem.builder().build());
        assertThat(cart.getCartItems()).hasSize(1);
    }

    @Test
    @DisplayName("two carts built by the builder do not share their item list")
    void eachCartGetsItsOwnList() {
        Cart first = Cart.builder().userId(1L).build();
        Cart second = Cart.builder().userId(2L).build();

        first.getCartItems().add(CartItem.builder().build());

        assertThat(second.getCartItems()).isEmpty();
    }

    @Test
    @DisplayName("the no-args constructor is present for JPA")
    void hasANoArgsConstructor() {
        Cart cart = new Cart();

        assertThat(cart.getId()).isNull();
        assertThat(cart.getUserId()).isNull();
    }

    @Test
    @DisplayName("the all-args constructor keeps the declaration order")
    void allArgsConstructorOrder() {
        LocalDateTime created = LocalDateTime.of(2026, 1, 1, 10, 0);
        LocalDateTime updated = LocalDateTime.of(2026, 1, 2, 10, 0);
        List<CartItem> items = new ArrayList<>();

        Cart cart = new Cart(7L, 42L, items, created, updated);

        assertThat(cart.getId()).isEqualTo(7L);
        assertThat(cart.getUserId()).isEqualTo(42L);
        assertThat(cart.getCartItems()).isSameAs(items);
        assertThat(cart.getCreatedAt()).isEqualTo(created);
        assertThat(cart.getUpdatedAt()).isEqualTo(updated);
    }

    @Test
    @DisplayName("every setter works")
    void settersWork() {
        Cart cart = new Cart();
        LocalDateTime now = LocalDateTime.now();

        cart.setId(7L);
        cart.setUserId(42L);
        cart.setCartItems(new ArrayList<>());
        cart.setCreatedAt(now);
        cart.setUpdatedAt(now);

        assertThat(cart.getId()).isEqualTo(7L);
        assertThat(cart.getUserId()).isEqualTo(42L);
        assertThat(cart.getCartItems()).isEmpty();
        assertThat(cart.getCreatedAt()).isEqualTo(now);
        assertThat(cart.getUpdatedAt()).isEqualTo(now);
    }

    // mapping ------------------------------------------------------------------

    @Test
    @DisplayName("is mapped to the 'cart' table")
    void isMappedToTheCartTable() {
        assertThat(Cart.class.getAnnotation(Entity.class)).isNotNull();
        assertThat(Cart.class.getAnnotation(Table.class).name()).isEqualTo("cart");
    }

    @Test
    @DisplayName("the id is generated by the database identity column")
    void idIsAnIdentityColumn() throws Exception {
        Field id = field("id");

        assertThat(id.getAnnotation(Id.class)).isNotNull();
        assertThat(id.getAnnotation(GeneratedValue.class).strategy()).isEqualTo(GenerationType.IDENTITY);
    }

    @Test
    @DisplayName("user_id is unique and not nullable - one cart per customer")
    void userIdIsUniqueAndMandatory() throws Exception {
        Column column = field("userId").getAnnotation(Column.class);

        assertThat(column.name()).isEqualTo("user_id");
        assertThat(column.unique()).isTrue();
        assertThat(column.nullable()).isFalse();
    }

    @Test
    @DisplayName("the items cascade and are orphan removed, so clearing the list deletes the rows")
    void itemsCascadeAndAreOrphanRemoved() throws Exception {
        OneToMany oneToMany = field("cartItems").getAnnotation(OneToMany.class);

        assertThat(oneToMany.mappedBy()).isEqualTo("cart");
        assertThat(oneToMany.cascade()).containsExactly(CascadeType.ALL);
        assertThat(oneToMany.orphanRemoval()).isTrue();
        assertThat(oneToMany.fetch()).isEqualTo(FetchType.LAZY);
    }

    @Test
    @DisplayName("created_at is stamped once and is never updatable")
    void createdAtIsImmutable() throws Exception {
        Field createdAt = field("createdAt");
        Column column = createdAt.getAnnotation(Column.class);

        assertThat(createdAt.getAnnotation(CreationTimestamp.class)).isNotNull();
        assertThat(column.name()).isEqualTo("created_at");
        assertThat(column.updatable()).isFalse();
        assertThat(column.nullable()).isFalse();
    }

    @Test
    @DisplayName("updated_at is refreshed on every write")
    void updatedAtIsRefreshed() throws Exception {
        Field updatedAt = field("updatedAt");
        Column column = updatedAt.getAnnotation(Column.class);

        assertThat(updatedAt.getAnnotation(UpdateTimestamp.class)).isNotNull();
        assertThat(column.name()).isEqualTo("updated_at");
        assertThat(column.nullable()).isFalse();
    }
}

