spring.application.name=agent-service

server.port=9060

spring.datasource.url=jdbc:postgresql://localhost:5432/agentdb
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000


#redis keys expire after this much inactivity
agent.session.ttl-minutes=60

#anthropic API key for LLM calls
anthropic.url=${ANTHROPIC_URL}
anthropic.api.key=${ANTHROPIC_API_KEY}
anthropic.api.model= claude-sonnet-4-20250514
anthropic.api.max-tokens=1000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#eureka configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka